<?php
return [
    'User'         => \App\User::class,
    'Type'         => \App\Type::class,
    'TradeStatus'  => \App\TradeStatus::class,
    'TradeHistory' => \App\TradeHistory::class,
    'Trade'        => \App\Trade::class,
    'Subdivision'  => \App\Subdivision::class,
    'Stock'        => \App\Stock::class,
    'Setting'      => \App\Setting::class,
    'Role'         => \App\Role::class,
    'Requisite'    => \App\Requisite::class,
    'Report'       => \App\Report::class,
    'Product'      => \App\Product::class,
    'Ppc'          => \App\Ppc::class,
    'Permission'   => \App\Permission::class,
    'Log'          => \App\Log::class,
    'Image'        => \App\Image::class,
    'FieldParam'   => \App\FieldParam::class,
    'Field'        => \App\Field::class,
    'Client'       => \App\Client::class,
    'Classes'      => \App\Classes::class,
    'Category'     => \App\Category::class,
];